# Generated by Django 5.0.2 on 2024-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha', models.DateField()),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
